# Generated by Django 4.0.1 on 2022-01-14 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNABDocumentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'DEBITO'), (2, 'BOLETO'), (3, 'FINANCIAMENTO'), (4, 'CREDITO'), (5, 'RECEBIMENTO_EMPRESTIMO'), (6, 'VENDAS'), (7, 'RECEBIMENTO_TED'), (8, 'RECEBIMENTO_DOC'), (9, 'ALUGUEL')])),
                ('date', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('store_owner', models.CharField(max_length=14)),
                ('store_name', models.CharField(max_length=19)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filepath', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'FINISHED')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=19, unique=True)),
                ('owner', models.CharField(max_length=14)),
                ('balance', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
